---
- name: Sync Database and upgrade System
  community.general.apk:
    upgrade: yes
    update_cache: yes
  become: true

- name: Install Docker Dependencies
  community.general.apk:
    name:
      - py3-pip
      - python3-dev
      - libffi-dev
      - openssl-dev
      - gcc
      - libc-dev
      - make
    state: present
  become: true

- name: Install Docker packages
  community.general.apk:
    name:
      - docker
      - docker-compose
    state: present
  become: true
...