---
- hosts: nodes

  tasks:
    - name: Update cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Remove unwanted packages
      become: true
      import_tasks: tasks/apt-remove.yml

    - name: Install required packages
      become: true
      import_tasks: tasks/apt-install.yml
