---
- name: Install an AUR helper
  kewlfft.aur.aur:
    use: makepkg
    name: yay
    state: present

- name: Install packages from the AUR
  kewlfft.aur.aur:
    use: yay
    name:
      - lf
      - pipes.sh
    state: present
