---
# This role is a example for installing basically tool

- name: install console tools
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - sudo
    - bash-completion
    - unzip
    - tar
    - dnsutils
    - htop
    - nmap
    - tree
    - tmux
    - screen
    - net-tools
    - ssl-cert
    - mc
    - openssl
    - lsb-release

- name: install editors
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - vim
    - nano

- name: install web sync tools
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - curl
    - rsync
    - wget
    - curl
    - apt-transport-https