# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV["LC_ALL"] = "en_US.UTF-8"

# DELETE OR ADD FURTHER ENTRIES DOWN BELOW
# AND CHANGE IPs & HOSTNAMES, IF NEEDED
boxes = [
  {
    :name => "calvin",
    :cpus => "2",
    :memory => "4096",
    :address => "192.168.56.31"
  },
  {
    :name => "hobbes",
    :cpus => "2",
    :memory => "4096",
    :address => "192.168.56.32"
  }
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/arch"
  config.ssh.forward_agent = true
  boxes.each do |vars|
    config.vm.define vars[:name] do |machine|
      machine.vm.hostname = vars[:name]
      machine.vm.provider "libvirt" do |lbv|
        lbv.driver = "kvm"
        lbv.memory = vars[:memory]
        lbv.cpus = vars[:cpus]
      end
      machine.vm.network :private_network, ip: vars[:address]
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "file", source: "./certificates/ansible_ssh.pub", destination: "~/ansible_ssh.pub"
      machine.vm.provision "file", source: "./certificates/mirrorlist", destination: "/tmp/mirrorlist"
      machine.vm.provision "shell", inline: "/bin/cp -rf /tmp/mirrorlist /etc/pacman.d/mirrorlist"
      machine.vm.provision "shell", path: "./bin/install-certificate.sh"
      machine.vm.provision "shell", path: "./bin/packages-pac.sh"
    end
  end
end
